# Generated by Django 3.0.4 on 2020-04-14 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('mobNo', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[6-9]\\d{9}$', 'Enter a valid Mobile Number.')], verbose_name='mobile number')),
                ('aadhaarNo', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{12}', 'Enter a valid Aadhaar Number.')], verbose_name='aadhaar number')),
                ('first_name', models.CharField(max_length=60, verbose_name='first name')),
                ('last_name', models.CharField(max_length=60, verbose_name='last name')),
                ('username', models.CharField(max_length=255)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_bidder', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
