# Generated by Django 3.0.4 on 2020-04-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountuser_org_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='org_owner',
        ),
    ]
