# Generated by Django 3.0.4 on 2020-04-14 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountuser_org_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='org_owner',
        ),
    ]
