# Generated by Django 3.0.4 on 2020-04-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_accountuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='is_orgadmin',
            field=models.BooleanField(default=False),
        ),
    ]
