# Generated by Django 3.0.4 on 2020-04-14 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0007_auto_20200415_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvDetails',
            fields=[
                ('tenderID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('descrip', models.CharField(max_length=300, verbose_name='Description')),
                ('dept', models.CharField(max_length=60, verbose_name='Department')),
                ('state', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=10)),
                ('bid_start_date', models.DateTimeField(auto_now_add=True, verbose_name='Bidding Opening Date')),
                ('bid_end_date', models.DateTimeField(verbose_name='Bidding Closing Date')),
                ('part_start_date', models.DateTimeField(verbose_name='Uploading Opening Date')),
                ('part_end_date', models.DateTimeField(verbose_name='Uploading Closing Date')),
                ('comb_start_date', models.DateTimeField(verbose_name='Combining Opening Date')),
                ('comb_end_date', models.DateTimeField(verbose_name='Combining Closing Date')),
                ('advFile', models.FileField(upload_to='')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Org', verbose_name='Organisation')),
            ],
        ),
    ]
