# Generated by Django 3.0.4 on 2020-04-14 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advposts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advdetails',
            name='bid_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Bidding Opening Date'),
        ),
    ]
