# Generated by Django 3.0.4 on 2020-04-21 08:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('advposts', '0003_auto_20200415_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advdetails',
            name='tenderID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
