# Generated by Django 3.0.4 on 2020-04-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advposts', '0004_auto_20200421_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddetails',
            name='bidID',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
