# Generated by Django 3.0.4 on 2020-04-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advposts', '0005_auto_20200422_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddetails',
            name='bidID',
            field=models.CharField(blank=True, max_length=16, primary_key=True, serialize=False),
        ),
    ]
