# Generated by Django 3.0.4 on 2020-05-10 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advposts', '0007_advdetails_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='advdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='advdetails',
            name='advFile',
            field=models.FileField(upload_to='advert_doc'),
        ),
    ]
