# Generated by Django 3.0.4 on 2020-08-29 15:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('advposts', '0010_biddetails_partholderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddetails',
            name='bidID',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='biddetails',
            name='bidPartID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
