# Generated by Django 3.0.4 on 2020-04-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_auto_20200414_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgowner',
            options={'verbose_name': 'Combiner', 'verbose_name_plural': 'Combiner'},
        ),
    ]
