# Generated by Django 3.0.4 on 2020-04-14 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_orgowner_combiner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgowner',
            name='Combiner',
        ),
    ]
