# Generated by Django 3.0.4 on 2020-04-15 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org', '0007_auto_20200415_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='OrgOwner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.OrgOwner', verbose_name='Combiner'),
        ),
        migrations.AlterField(
            model_name='org',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='org',
            name='location',
            field=models.CharField(default=None, max_length=300, null=True, verbose_name='Address'),
        ),
    ]
