# Generated by Django 3.0.4 on 2020-04-15 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org', '0008_auto_20200415_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='OrgOwner',
        ),
        migrations.AlterField(
            model_name='org',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner/Combiner'),
        ),
    ]
